# Generated by Django 3.0.7 on 2020-08-09 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='director_id',
            new_name='director',
        ),
    ]
